### ISSUE TITLE
Benchmark against distribution-matching resnet

### ISSUE THREAD

**Issue by jdayton3** [jdayton3/Confounded#24]
We need to figure out how to run [this code](https://github.com/ushaham/BatchEffectRemoval) and include it in our benchmarks.

**Comment by edj4960** [comment]
:+1:

**Comment by jdayton3** [comment]
Couldn't get the code to run, unfortunately. It needed a large dataset with only two batches that were completely balanced, and few of our datasets matched those criteria.
