### ISSUE TITLE
Throws error when not all str columns are given to META_COLS

### ISSUE THREAD

**Issue by edj4960** [jdayton3/Confounded#34]
**ERROR**
When the user tries to set META_COLS to different values than the standard of all columns with string names the code will throw an "InvalidArgumentError" that reads: 

Input to reshape is a tensor with 78500 values, but the requested shape requires a multiple of **784**
[[Node: autoencoder/Reshape = Reshape[T=DT_FLOAT, Tshape=DT_INT32,
_device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_autoencoder/Placeholder_0_0, autoencoder/Reshape/shape)]]

the 784 is referencing the number of columns which tensor flow expected to receive, however now it is receiving an extra column because that column was not included in META_COLS.

**POSSIBLE SOLUTION**
A possible way to fix this issue is to ignore the string name columns that weren't chosen to be added to META_COLS.

Another error occurs if the first column 'Batch' is left out from META_COLS. The error reads:
ValueError: could not convert string to float: 'B'

This error is understandable because the Batch column is all letters and it doesn't make sense that this column would be opted out. In future versions columns without integer or float point values should be **required** to be added to META_COLS.

**Comment by jdayton3** [comment]
I'm going to just remove the `META_COLS` parameter. Because we always want to adjust quantitative values and never want to (never can) adjust discrete values.
